#!/usr/bin/env bash
## 
# Installs and configures HAproxy on lb-01 server
# Configure HAproxy so that it sends traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# HAprorxy should be managed via an init script
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 207620-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 207620-web-02 35.153.255.237:80 check\n\tserver 207620-web-01 54.237.14.239:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
