#!/usr/bin/env bash
# Script to listen the port 80 (make fix short and sweet)
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
sudo pkill -o nginx
