#!/usr/bin/env bash
# A script that displays numbers from 1 to 20 and:
# Displays 4 and then 'bad luck from China' for 4th loop
# Displays 9 and then 'bad luck from Japan' for 9th loop
# Displays 17 and then 'bad luck from Italy' for 17th loop

num=1

while [ $num -le 20 ]
do
	echo "$num"
	case $num in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( num++ ))
done
