#!/usr/bin/env bash
# Script that displays content of the current directory
# In a list format where only part of the name after the
# Dash is displayed

list=$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done
